/* Generated by lastchange.py, do not edit.*/

#ifndef GPU_CONFIG_GPU_LISTS_VERSION_H_
#define GPU_CONFIG_GPU_LISTS_VERSION_H_

#define GPU_LISTS_VERSION "55132f110218a75dc6a4c2c20269efd6e3059177"

#endif  // GPU_CONFIG_GPU_LISTS_VERSION_H_
