/* Generated by lastchange.py, do not edit.*/

#ifndef GPU_CONFIG_GPU_LISTS_VERSION_H_
#define GPU_CONFIG_GPU_LISTS_VERSION_H_

#define GPU_LISTS_VERSION "0572f658aba8bf6b19f4c4e46d981505b7f6921b"

#endif  // GPU_CONFIG_GPU_LISTS_VERSION_H_
