/* Generated by lastchange.py, do not edit.*/

#ifndef GPU_CONFIG_GPU_LISTS_VERSION_H_
#define GPU_CONFIG_GPU_LISTS_VERSION_H_

#define GPU_LISTS_VERSION "5f7bda9548b4b88b10ea968649985fae793a15b4"

#endif  // GPU_CONFIG_GPU_LISTS_VERSION_H_
