# Copyright (c) 2023-2025 Haitai FangYuan Co., Ltd.
# Redistribution and use in source and binary forms, with or without modification,
# are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice, this list of
#    conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice, this list
#    of conditions and the following disclaimer in the documentation and/or other materials
#    provided with the distribution.
#
# 3. Neither the name of the copyright holder nor the names of its contributors may be used
#    to endorse or promote products derived from this software without specific prior written
#    permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
# THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
# PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR
# CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
# EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
# PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
# OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
# WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
# OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
# ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

import("//build/config/ohos/config.gni")
import("//ohos/adapter/multiprocess/multiprocess.gni")
import("//testing/test.gni")

component("multiprocess") {
  sources = [
    "app_spawn_communication.cc",
    "app_spawn_communication.h",
    "child_process_starter.cc",
    "child_process_starter.h",
    "scoped_socket.cc",
    "scoped_socket.h",
    "unix_domain_socket_helper.cc",
    "unix_domain_socket_helper.h"
  ]

  deps = [
    "//ohos/adapter/multiprocess/gpu:gpu",

  ]

  if (enable_isolate_process) {
    deps += [
      "//ohos/adapter/multiprocess/isolate_process:isolate_process",
    ]
    defines = [
      "ENABLE_START_ISOLATE_PROCESS"
    ]
  }

  public_deps = [
    "//third_party/aki:aki_jsbind",
  ]

  cflags = [
    "-Wno-error=delete-incomplete",
    "-Wno-error=writable-strings",
    "-Wno-error=parentheses-equality"
  ]
}

test("multiprocess_unittests") {
  sources = [
    "command_line/command_line_unittests.cc",
    "gpu/gpu_native_ipc_proxy_unittests.cc",
    "gpu/gpu_native_ipc_stub_unittests.cc",
    "gpu/gpu_native_process_host_unittests.cc",
    "gpu/gpu_native_process_test_utils.cc",
    "gpu/gpu_native_process_test_utils.h",
    "gpu/gpu_native_process_unittests.cc",
    "gpu/native_window_parcel_unittests.cc"
  ]

  deps = [
    "//ohos/adapter/multiprocess/command_line:command_line",
    "//ohos/adapter/multiprocess/gpu:gpu",
    "//ohos/adapter/test:run_all_unittests",
    "//testing/gmock",
    "//testing/gtest"
  ]
}
