# Copyright 2023 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//build/config/ohos/config.gni")

component("ime_adapter") {
  sources = [
    "input_method_ohos_adapter.h",
    "input_method_ohos_adapter.cc"
  ]

  deps = [ "//third_party/aki:aki_jsbind" ]
}