# Copyright (c) 2024 Huawei Device Co., Ltd. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//build/config/ohos/config.gni")

component("bluetooth_adapter") {
  sources = [
    "bluetooth_adapter.cc",
    "bluetooth_adapter.h",
    "bluetooth_ble_attribute_adapter.cc",
    "bluetooth_ble_attribute_adapter.h",
    "bluetooth_low_energy_adapter.cc",
    "bluetooth_low_energy_adapter.h",
  ]

  deps = [ "//third_party/aki:aki_jsbind" ]
}