# Copyright (c) 2024 Huawei Device Co., Ltd. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//build/config/ohos/config.gni")

component("command_line") {
  sources = [
    "command_line_helper.cc",
    "command_line_helper.h",
    "command_line.cc",
    "command_line.h",
    "command_line_switches.cc",
    "command_line_switches.h"
  ]

  public_deps = [
    "//third_party/aki:aki_jsbind",
  ]

  cflags = [
    "-pthread",
  ]
}
