# Copyright 2014 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//mojo/public/tools/bindings/mojom.gni")
import("//arkweb/build/features/features.gni")

mojom("mojom") {
  sources = [ "web_cache.mojom" ]

  enabled_features = []
  if (arkweb_inject_offline_resource) {
    enabled_features += [ "arkweb_inject_offline_resource" ]
  }
}

