# Copyright (c) 2024 Huawei Device Co., Ltd. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//build/config/ohos/config.gni")

component("xcomponent") {
    sources = [
      "adapter/window_adapter.cc",
      "adapter/window_adapter.h",
      "event/gesture_event_receiver.cc",
      "event/gesture_event_common.h",
      "event/input_event_common.h",
      "event/window_event_receiver.cc",
      "event/window_event_common.h",
      "event/native_event_listener.h",
      "event/native_event_receiver.cc",
      "event/native_event_receiver.h",
      "renderer/xcomponent_impl.cc",
      "renderer/xcomponent_impl.h",
      "xcomponent_manager.cc",
      "xcomponent_manager.h",
      "xcomponent_delegate.h"
    ]

    cflags = [
      "-Wno-error=delete-incomplete",
      "-Wno-error=writable-strings",
      "-Wno-error=parentheses-equality"
    ]

    deps = [ "//third_party/aki:aki_jsbind" ]

    libs = [
      "hilog_ndk.z",
      "ace_ndk.z",
      "ace_napi.z",
    ]
}
