# Copyright (c) 2025 Huawei Device Co., Ltd.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import("//testing/test.gni")
import("//arkweb/build/features/features.gni")

test("network_unittests") {
  testonly = true

  sources = [
    "//arkweb/chromium_ext/services/network/tests/url_loader_ext_unittest.cc",
  ]

  include_dirs = [
    "//arkweb/chromium_ext/services/network/",
  ]

  cflags = [ "-fno-access-control" ]
  cflags_cc = [ "-fno-access-control" ]

  deps = [
    "//arkweb/chromium_ext/services/network:network_service",
    "//base",
    "//net/third_party/quiche",
    "//services/test:run_all_unittests",
    "//testing/gmock",
    "//testing/gtest",
  ]
}