# Copyright (c) 2026 Huawei Device Co., Ltd.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import("//testing/libfuzzer/fuzzer_test.gni")

fuzzer_test("trace_event_ohos_fuzzer") {
  sources = [ "trace_event_ohos_fuzzer.cpp" ]
  include_dirs = [
    "//cef",
    "//ohos_nweb/include",
    "//ohos_nweb/src",
    "//base",
  ]
  deps = [
    "//arkweb/ohos_adapter_ndk:adapter_ndk_stub",
    "//cef:libcef_static",
    "//ohos_nweb:cef_nweb",
    "//ohos_nweb:nweb_sources",
    "//base",
  ]
}

## Trace Event Fuzzers
group("trace_event_ohos_fuzzers") {
  testonly = true
  deps = [
    ":trace_event_ohos_fuzzer",
  ]
}