# Copyright (c) 2022 Huawei Device Co., Ltd.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import("//build/buildflag_header.gni")
import("//build/config/features.gni")
import("//build/config/ohos/config.gni")
import("//ohos_nweb/src/nweb_sysevent.gni")
import("//tools/grit/grit_rule.gni")
import("//tools/grit/repack.gni")

component("nweb_hilog") {
  sources = [ "src/nweb_hilog.h" ]

  include_dirs = ohos_src_includes
  deps = [
    "//ohos_glue:ohos_adapter_glue_source",
  ]
}

#################################################

config("cef_nweb_config") {
  include_dirs = [
    "include",
    "src",
    "src/cef_delegate",
    "src/sysevent",
    "//cef",
    "//cef/include",
    "//cef/libcef/browser/net_service",
    "//third_party/skia",
  ]
  include_dirs += ohos_src_includes

  #ifdef OHOS_PERFORMANCE_PERSISTENT_TASK
  if (defined(ohos_performance_persistent_task) &&
      ohos_performance_persistent_task) {
    include_dirs += [
      "browser/performance_manager",
      "browser/performance_manager/mechanisms",
      "browser/performance_manager/policies",
    ]
  }

  #endif

  defines = [ "USING_CHROMIUM_INCLUDES" ]

  if (product_name == "rk3568") {
    defines += [ "RK3568" ]
  }

  if (report_sys_event) {
    defines += [ "REPORT_SYS_EVENT" ]
  }
}

component("cef_nweb") {
  configs += [
    ":cef_nweb_config",
    ":nweb_config",
  ]

  if (use_libfuzzer) {
    configs -= [ "//build/config/gcc:symbol_visibility_hidden" ]
    configs += [ "//build/config/gcc:symbol_visibility_default" ]
    cflags = [ "-DOHOS_FUZZ_COMPILE_ERROR_FIX" ]
  }

  deps = [
    "//ohos_glue:ohos_adapter_glue_source",
    "//third_party:huawei_securec",
  ]

  sources = [
    "src/cef_delegate/nweb_access_request_delegate.cc",
    "src/cef_delegate/nweb_access_request_delegate.h",
    "src/cef_delegate/nweb_accessibility_node_info_impl.cc",
    "src/cef_delegate/nweb_accessibility_node_info_impl.h",
    "src/cef_delegate/nweb_adsblock_manager_delegate.cc",
    "src/cef_delegate/nweb_adsblock_manager_delegate.h",
    "src/cef_delegate/nweb_application.cc",
    "src/cef_delegate/nweb_application.h",
    "src/cef_delegate/nweb_console_log_impl.cc",
    "src/cef_delegate/nweb_console_log_impl.h",
    "src/cef_delegate/nweb_context_menu_params_impl.cc",
    "src/cef_delegate/nweb_context_menu_params_impl.h",
    "src/cef_delegate/nweb_controller_handler_impl.cc",
    "src/cef_delegate/nweb_controller_handler_impl.h",
    "src/cef_delegate/nweb_cookie_manager_delegate.cc",
    "src/cef_delegate/nweb_cookie_manager_delegate.h",
    "src/cef_delegate/nweb_cursor_info_impl.cc",
    "src/cef_delegate/nweb_cursor_info_impl.h",
    "src/cef_delegate/nweb_data_base_delegate.cc",
    "src/cef_delegate/nweb_data_base_delegate.h",
    "src/cef_delegate/nweb_data_resubmission_callback_impl.cc",
    "src/cef_delegate/nweb_data_resubmission_callback_impl.h",
    "src/cef_delegate/nweb_date_time_chooser_impl.cc",
    "src/cef_delegate/nweb_date_time_chooser_impl.h",
    "src/cef_delegate/nweb_default_engine_init_args_impl.cc",
    "src/cef_delegate/nweb_default_engine_init_args_impl.h",
    "src/cef_delegate/nweb_default_engine_prefetch_args_impl.cc",
    "src/cef_delegate/nweb_default_engine_prefetch_args_impl.h",
    "src/cef_delegate/nweb_delegate.cc",
    "src/cef_delegate/nweb_delegate.h",
    "src/cef_delegate/nweb_display_listener.cc",
    "src/cef_delegate/nweb_display_listener.h",
    "src/cef_delegate/nweb_download_handler_delegate.cc",
    "src/cef_delegate/nweb_download_handler_delegate.h",
    "src/cef_delegate/nweb_event_handler.cc",
    "src/cef_delegate/nweb_event_handler.h",
    "src/cef_delegate/nweb_file_selector_params_impl.cc",
    "src/cef_delegate/nweb_file_selector_params_impl.h",
    "src/cef_delegate/nweb_find_delegate.cc",
    "src/cef_delegate/nweb_find_delegate.h",
    "src/cef_delegate/nweb_full_screen_exit_handler_impl.cc",
    "src/cef_delegate/nweb_full_screen_exit_handler_impl.h",
    "src/cef_delegate/nweb_geolocation_callback.cc",
    "src/cef_delegate/nweb_geolocation_callback.h",
    "src/cef_delegate/nweb_handler_delegate.cc",
    "src/cef_delegate/nweb_handler_delegate.h",
    "src/cef_delegate/nweb_history_list_impl.cc",
    "src/cef_delegate/nweb_history_list_impl.h",
    "src/cef_delegate/nweb_hit_test_result_impl.cc",
    "src/cef_delegate/nweb_hit_test_result_impl.h",
    "src/cef_delegate/nweb_image_options_impl.cc",
    "src/cef_delegate/nweb_image_options_impl.h",
    "src/cef_delegate/nweb_input_delegate.cc",
    "src/cef_delegate/nweb_input_delegate.h",
    "src/cef_delegate/nweb_inputevent_handler.h",
    "src/cef_delegate/nweb_inputmethod_client.h",
    "src/cef_delegate/nweb_js_dialog_result_impl.cc",
    "src/cef_delegate/nweb_js_dialog_result_impl.h",
    "src/cef_delegate/nweb_js_http_auth_result_impl.cc",
    "src/cef_delegate/nweb_js_http_auth_result_impl.h",
    "src/cef_delegate/nweb_js_ssl_error_result_impl.cc",
    "src/cef_delegate/nweb_js_ssl_error_result_impl.h",
    "src/cef_delegate/nweb_js_ssl_select_cert_result_impl.cc",
    "src/cef_delegate/nweb_js_ssl_select_cert_result_impl.h",
    "src/cef_delegate/nweb_gesture_event_result_impl.cc",
    "src/cef_delegate/nweb_gesture_event_result_impl.h",
    "src/cef_delegate/nweb_key_event_impl.cc",
    "src/cef_delegate/nweb_key_event_impl.h",
    "src/cef_delegate/nweb_preference_delegate.cc",
    "src/cef_delegate/nweb_preference_delegate.h",
    "src/cef_delegate/nweb_render_handler.cc",
    "src/cef_delegate/nweb_render_handler.h",
    "src/cef_delegate/nweb_resource_handler.cc",
    "src/cef_delegate/nweb_resource_handler.h",
    "src/cef_delegate/nweb_select_menu_bound_impl.cc",
    "src/cef_delegate/nweb_select_menu_bound_impl.h",
    "src/cef_delegate/nweb_touch_handle_hot_zone_impl.cc",
    "src/cef_delegate/nweb_touch_handle_hot_zone_impl.h",
    "src/cef_delegate/nweb_touch_handle_state_impl.cc",
    "src/cef_delegate/nweb_touch_handle_state_impl.h",
    "src/cef_delegate/nweb_url_resource_response_impl.cc",
    "src/cef_delegate/nweb_url_resource_response_impl.h",
    "src/cef_delegate/nweb_web_storage_delegate.cc",
    "src/cef_delegate/nweb_web_storage_delegate.h",
    "src/cef_delegate/nweb_web_storage_origin_impl.cc",
    "src/cef_delegate/nweb_web_storage_origin_impl.h",
    "src/cef_delegate/nweb_custom_keyboard_handler_impl.cc",
    "src/cef_delegate/nweb_custom_keyboard_handler_impl.h",
    "src/sysevent/event_reporter.cc",
    "src/sysevent/event_reporter.h",
    "src/sysevent/oh_web_performance_timing.cc",
    "src/sysevent/oh_web_performance_timing.h",
  ]

  #ifdef OHOS_SCHEME_HANDLER
  if (defined(ohos_scheme_handler) && ohos_scheme_handler) {
    sources += [
      "src/cef_delegate/nweb_pipe_resource_handler.cc",
      "src/cef_delegate/nweb_pipe_resource_handler.h",
      "src/cef_delegate/nweb_scheme_handler_factory.cc",
      "src/cef_delegate/nweb_scheme_handler_factory.h",
      "src/ndk/scheme_handler/arkweb_scheme_handler.cc",
      "src/ndk/scheme_handler/http_body_stream.cc",
      "src/ndk/scheme_handler/http_body_stream.h",
      "src/ndk/scheme_handler/resource_handler.cc",
      "src/ndk/scheme_handler/resource_handler.h",
      "src/ndk/scheme_handler/resource_request.cc",
      "src/ndk/scheme_handler/resource_request.h",
      "src/ndk/scheme_handler/response.cc",
      "src/ndk/scheme_handler/response.h",
    ]
  }

  #endif

  sources += [
    "src/ndk/arkweb_model.cc",
    "src/ndk/arkweb_native_javascript_execute_callback.cc",
    "src/ndk/arkweb_native_javascript_execute_callback.h",
    "src/ndk/arkweb_native_object.cc",
    "src/ndk/arkweb_native_object.h",
    "src/ndk/arkweb_native_web_message_callback.cc",
    "src/ndk/arkweb_native_web_message_callback.h",
  ]

  sources += [
    "src/cef_delegate/nweb_value_convert.cc",
    "src/cef_delegate/nweb_value_convert.h",
  ]

  #ifdef OHOS_HTML_SELECT
  if (defined(ohos_html_select) && ohos_html_select) {
    sources += [
      "src/cef_delegate/nweb_select_popup_menu_impl.cc",
      "src/cef_delegate/nweb_select_popup_menu_impl.h",
    ]
  }

  #endif

  #ifdef OHOS_DRAG_DROP
  if (defined(ohos_drag_drop) && ohos_drag_drop) {
    sources += [
      "src/cef_delegate/nweb_drag_data_impl.cc",
      "src/cef_delegate/nweb_drag_data_impl.h",
    ]
  }

  #endif // OHOS_DRAG_DROP

  #ifdef OHOS_PERFORMANCE_PERSISTENT_TASK
  if (defined(ohos_performance_persistent_task) &&
      ohos_performance_persistent_task) {
    sources += [
      "browser/performance_manager/mechanisms/background_task_holder.cc",
      "browser/performance_manager/mechanisms/background_task_holder.h",
      "browser/performance_manager/nweb_performance_manager.cc",
      "browser/performance_manager/nweb_performance_manager.h",
      "browser/performance_manager/policies/background_task_policy.cc",
      "browser/performance_manager/policies/background_task_policy.h",
      "browser/performance_manager/policies/ohos_bfcache_policy.cc",
      "browser/performance_manager/policies/ohos_bfcache_policy.h"
    ]
  }

  #endif

#if defined(OHOS_CUSTOM_VIDEO_PLAYER)
  if (defined(ohos_custom_video_player) && ohos_custom_video_player) {
    sources += [
      "src/cef_delegate/custom_media_player_impl.cc",
      "src/cef_delegate/custom_media_player_impl.h",
      "src/native_media_player/nweb_native_media_player_handler_impl.cc",
      "src/native_media_player/nweb_native_media_player_handler_impl.h",
      "src/native_media_player/nweb_media_info_impl.cc",
      "src/native_media_player/nweb_media_info_impl.h",
    ]
  }
#endif // OHOS_CUSTOM_VIDEO_PLAYER

  deps += [
    "//base:base",
    "//content/public/common",
    "//ui/events/keycodes:x11",
  ]

  if (defined(ohos_nweb_ex) && ohos_nweb_ex) {
    deps += [ "//ohos_nweb_ex/overrides/ohos_nweb" ]
  } else {
    sources += [ "src/cef_delegate/nweb_delegate_ohos.cc" ]
  }
}

#################################################

config("nweb_config") {
  defines = [
    "OHOS_NWEB",
    "OS_OHOS",
    "USE_CEF",
  ]

  if (gpu_switch == "off") {
    defines += [ "GPU_RK3568" ]
  }

  include_dirs = [
    "include",
    "src",
  ]

  include_dirs += ohos_src_includes
}

component("nweb_sources") {
  configs += [
    ":nweb_config",
    ":cef_nweb_config",
  ]

  sources = [
    "include/nweb.h",
    "include/nweb_access_request.h",
    "include/nweb_accessibility_event_callback.h",
    "include/nweb_accessibility_node_info.h",
    "include/nweb_console_log.h",
    "include/nweb_controller_handler.h",
    "include/nweb_cookie_manager.h",
    "include/nweb_data_resubmission_callback.h",
    "include/nweb_download_callback.h",
    "include/nweb_download_manager.h",
    "include/nweb_engine.h",
    "include/nweb_find_callback.h",
    "include/nweb_geolocation_callback_interface.h",
    "include/nweb_handler.h",
    "include/nweb_javascript_result_callback.h",
    "include/nweb_js_dialog_result.h",
    "include/nweb_js_http_auth_result.h",
    "include/nweb_key_event.h",
    "include/nweb_preference_delegate.h",
    "include/nweb_value.h",
    "include/nweb_value_callback.h",
    "src/capi/nweb_app_client_extension_callback.h",
    "src/capi/nweb_storage_extension_callback.h",
    "src/nweb_adsblock_manager_impl.cc",
    "src/nweb_adsblock_manager_impl.h",
    "src/nweb_cookie_manager_delegate_interface.h",
    "src/nweb_cookie_manager_impl.cc",
    "src/nweb_cookie_manager_impl.h",
    "src/nweb_data_base_impl.cc",
    "src/nweb_data_base_impl.h",
    "src/nweb_delegate_adapter.cc",
    "src/nweb_delegate_adapter.h",
    "src/nweb_delegate_interface.h",
    "src/nweb_download_manager_impl.cc",
    "src/nweb_download_manager_impl.h",
    "src/nweb_engine_impl.cc",
    "src/nweb_engine_impl.h",
    "src/nweb_hilog.h",
    "src/nweb_impl.cc",
    "src/nweb_impl.h",
    "src/nweb_input_handler.cc",
    "src/nweb_input_handler.h",
    "src/nweb_inputmethod_handler.cc",
    "src/nweb_inputmethod_handler.h",
    "src/nweb_output_handler.cc",
    "src/nweb_output_handler.h",
    "src/nweb_url_resource_error_impl.hh",
    "src/nweb_url_resource_request_impl.cc",
    "src/nweb_url_resource_request_impl.h",
    "src/nweb_web_storage_impl.cc",
    "src/nweb_web_storage_impl.h",
    "src/nweb_first_meaningful_paint_details_impl.cc",
    "src/nweb_first_meaningful_paint_details_impl.h",
    "src/nweb_largest_contentful_paint_details_impl.cc",
    "src/nweb_largest_contentful_paint_details_impl.h",
    "src/nweb_imf_cursor_info_adapter_impl.cc",
    "src/nweb_imf_cursor_info_adapter_impl.h",
    "src/nweb_imf_input_attribute_adapter_impl.cc",
    "src/nweb_imf_input_attribute_adapter_impl.h",
    "src/nweb_imf_selection_range_adapter_impl.cc",
    "src/nweb_imf_selection_range_adapter_impl.h",
    "src/nweb_imf_text_config_adapter_impl.cc",
    "src/nweb_imf_text_config_adapter_impl.h",
  ]

  #if defined(OHOS_NAVIGATION)
  if (defined(ohos_navigation) && ohos_navigation) {
    sources += [
      "src/nweb_load_committed_details_impl.cc",
      "src/nweb_load_committed_details_impl.h",
    ]
  }

  #endif  // defined(OHOS_NAVIGATION)

  if (!defined(ohos_nweb_ex) || !ohos_nweb_ex) {
    sources += [ "src/download/web_downloader.cc" ]
  }

  deps = [
    ":cef_nweb",
    ":nweb_hilog",
    "//third_party/boringssl",
    "//ohos_glue:ohos_nweb_glue_source",
  ]

  #if defined(OHOS_NO_STATE_PREFETCH)
  if (defined(ohos_no_state_prefetch) && ohos_no_state_prefetch) {
    deps += [ "//third_party/boringssl" ]
  }  #endif  // defined(OHOS_NO_STATE_PREFETCH)

  public_deps = [ "//third_party/abseil-cpp:absl" ]

  deps += [
    "//ohos_glue:ohos_adapter_glue_source",
  ]
}

#################################################

config("ohosnweb_core_config") {
  defines = [
    "OHOS_NWEB",
    "OS_OHOS",
  ]

  include_dirs = [
    "//cef",
    "//cef/include",
  ]

  include_dirs += ohos_src_includes
}

shared_library("libnweb_render") {
  configs += [ "//build/config/sanitizers:cfi_config" ]
  defines = [ "OHOS_NWEB" ]

  include_dirs = [ "include" ]
  include_dirs += ohos_src_includes

  sources = [
    "src/nweb_render_main.cc",
    "src/set_renderer_seccomp_policy.cc",
  ]

  deps = [
    ":nweb_hilog",
    "//cef:libcef_dll_wrapper",
    "//cef:libweb_engine",
    "//sandbox:sandbox",
  ]
}

#################################################

source_set("unittests") {
  testonly = true

  configs += [
    ":nweb_config",
    ":cef_nweb_config",
  ]

  include_dirs = [ "//ppapi/lib/gl/include" ]

  sources = [
    "src/cef_delegate/nweb_delegate_unittest.cc",
    "src/cef_delegate/nweb_event_handler_unittest.cc",
    "src/cef_delegate/nweb_handler_delegate_unittest.cc",
    "src/cef_delegate/nweb_pipe_resource_handler_unittest.cc",
    "src/cef_delegate/nweb_preference_delegate_unittest.cc",
    "src/cef_delegate/nweb_render_handler_unittest.cc",
    "src/cef_delegate/nweb_scheme_handler_factory_unittest.cc",
    "src/ndk/scheme_handler/http_body_stream_unittest.cc",
    "src/ndk/scheme_handler/resource_handler_unittest.cc",
    "src/ndk/scheme_handler/resource_request_unittest.cc",
    "src/ndk/scheme_handler/response_unittest.cc",
    "src/nweb_impl_unittest.cc",
    "src/nweb_input_handler_unittest.cc",
    "src/nweb_inputmethod_handler_unittest.cc",
    "src/set_renderer_seccomp_policy_unittest.cc",
  ]

  deps = [
    ":nweb_sources",
    ":cef_nweb",
    "//third_party/boringssl",
    "//ohos_glue:ohos_nweb_glue_source",
    "//ohos_glue:ohos_adapter_glue_source",
    "//third_party/boringssl",
    "//components/web_cache/browser:browser",
    "//cef:libcef_static",
  ]

  public_deps = [
    "//testing/gmock",
    "//third_party/abseil-cpp:absl",
  ]
}
