# Copyright (c) 2023-2025 Haitai FangYuan Co., Ltd.
# Redistribution and use in source and binary forms, with or without modification,
# are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice, this list of
#    conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice, this list
#    of conditions and the following disclaimer in the documentation and/or other materials
#    provided with the distribution.
#
# 3. Neither the name of the copyright holder nor the names of its contributors may be used
#    to endorse or promote products derived from this software without specific prior written
#    permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
# THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
# PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR
# CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
# EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
# PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
# OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
# WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
# OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
# ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

import("//build/config/ohos/config.gni")
import("//build/config/chrome_build.gni")

component("web_entry") {
    sources = [
      "chrome/chrome_loader.cc",
      "chrome/chrome_loader.h",
      "shell/content_shell_loader.cc",
      "shell/content_shell_loader.h",
      "web_entry_init.cc",
      "web_entry_init.h",
      "web_entry.cc",
      "web_entry.h",
      "web_loader_factory.cc",
      "web_loader.cc",
      "web_loader.h",
    ]

    if (ohos_build_target == "content_shell") {
      defines = [ "USE_LOADER_TARGET=0" ]
    } else if (ohos_build_target == "chromium") {
      defines = [ "USE_LOADER_TARGET=1" ]
    } else {
      assert(true, "$ohos_build_target target builds are not supported on ohos")
    }

    cflags = [
      "-Wno-error=delete-incomplete",
      "-Wno-error=writable-strings",
      "-Wno-error=parentheses-equality"
    ]

    deps = [
      "//ohos/adapter/life_cycle:life_cycle",
      "//ohos/adapter/dev_config:dev_config",
    ]

    libs = [ "hilog_ndk.z" ]
}
