# Copyright 2024 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//build/buildflag_header.gni")

buildflag_header("buildflags") {
  header = "buildflags.h"
}

source_set("prp_preload") {
  visibility = [
    "//net:net",
    "//cef:make_pack_header_resources"
  ]

  include_dirs = [ "//net/prp_preload/include" ]

  deps = [
    "//base",
    "//net/third_party/quiche",
  ]

  sources = [
    "src/disk_cache_backend_factory.cc",
    "src/disk_cache_file.cc",
    "src/page_res_parallel_preload_mgr_impl.cc",
    "src/res_parallel_preload_ctrler.cc",
    "src/preconnect_runner.cc",
    "src/res_preload_scheduler.cc",
    "src/res_request_info_cache_mgr.cc",
    "src/res_request_info_updater.cc",
  ]
}
