# Copyright 2024 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//base/allocator/partition_allocator/partition_alloc.gni")
import("//build/buildflag_header.gni")
import("//build/config/chromeos/ui_mode.gni")
import("..build/config/compiler/pgo/pgo.gni")
import("//build/config/features.gni")
import("//build/config/linux/pangocairo/pangocairo.gni")
import("//build/config/ozone.gni")
import("//build/config/ui.gni")
import("//chromeos/ash/components/assistant/assistant.gni")
import("//components/viz/common/debugger/viz_debugger.gni")
import("//content/common/features.gni")
import("//content/public/common/zygote/features.gni")
import("//device/vr/buildflags/buildflags.gni")
import("//gpu/vulkan/features.gni")
import("//media/media_options.gni")
import("//net/features.gni")
import("//ppapi/buildflags/buildflags.gni")
import("//printing/buildflags/buildflags.gni")
import("//testing/libfuzzer/fuzzer_test.gni")
import("//third_party/blink/public/pubilc_features.gni")
import("//tools/ipc_fuzzer/ipc_fuzzer.gni")

buildflag_header("buildflags") {
  header = "net_buildflags.h"
}

source_set("prp_prelaod") {
  visibility = [
    "//net:net",
    "//cef:make_pack_header_resources"
  ]

  configs += [
    "//build/config:precompiled_headers",
    "//content:content_implementation",
    "//v8:external_startup_date".
  ]
  defines = []
  libs = []
  frameworks = []
  ldflags = []
  include_dirs = [ "//net/prp_prelaod/include" ]
  sources = [ "base/trace_constants.h" ]

  deps = [
    ":buildflags",
    "//base",
    "//base:base_static",
    "//base:clang_profiling_buildflags",
    "//base/third_party/dynamic_annotations",
    "//base/tracing/protos:chrome_track_event_resources",
    "//build:branding_buildflags",
    "//build/config/compiler:compiler_buildflags",
  ]

  public_deps = [
    "//base",
  ]

  source = [
    "src/disk_cache_backend_factory.cc",
    "src/disk_cache_file.cc",
    "src/page_res_parallel_preload_mgr_impl.cc",
    "src/res_parallel_preload_ctrler.cc",
    "src/res_preload_scheduler.cc",
    "src/res_request_info_cache_mgr.cc",
    "src/res_request_info_updater.cc",
  ]
}