/* Generated by lastchange.py, do not edit.*/

#ifndef SKIA_EXT_SKIA_COMMIT_HASH_H_
#define SKIA_EXT_SKIA_COMMIT_HASH_H_

#define SKIA_COMMIT_HASH "0c63948756c5004a48de362ffbe2fd461e5339cf"

#endif  // SKIA_EXT_SKIA_COMMIT_HASH_H_
