/* Generated by lastchange.py, do not edit.*/

#ifndef SKIA_EXT_SKIA_COMMIT_HASH_H_
#define SKIA_EXT_SKIA_COMMIT_HASH_H_

#define SKIA_COMMIT_HASH "d7268f8245f2a6223db4f6eb1d732038a214c1a1"

#endif  // SKIA_EXT_SKIA_COMMIT_HASH_H_
