/* Generated by lastchange.py, do not edit.*/

#ifndef SKIA_EXT_SKIA_COMMIT_HASH_H_
#define SKIA_EXT_SKIA_COMMIT_HASH_H_

#define SKIA_COMMIT_HASH "c17fe9bc158c29de3cdd655ac73d14f52c17810a"

#endif  // SKIA_EXT_SKIA_COMMIT_HASH_H_
