# Copyright (c) 2025 Huawei Device Co., Ltd. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//components/crash/ohos/crashpad.gni")

component("crash_features") {
  sources = [
    "features.cc",
    "features.h",
  ]

  if (enable_crashpad) {
    defines = [ "ENABLE_CRASHPAD" ]
  }

  deps = [ "//base" ]
}