# Copyright (c) 2025 Huawei Device Co., Ltd. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

declare_args() {
  # The enable_crashpad is set to false default
  # when you want to use the crashpad system, please set enable_crashpad to true
  enable_crashpad = false
}