// Copyright 2013 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
//
// Distilled page content.

syntax = "proto2";

option optimize_for = LITE_RUNTIME;

package dom_distiller;

message DistilledPageProto {
  // The URLs used to create this page.
  required string url = 1;

  // The distilled HTML.
  required string html = 3;

  message Image {
    // Handle to the image. This could be the URL where the image was found.
    // The handle should be referenced verbatim in the HTML.
    required string name = 1;

    // The image data
    required bytes data = 2;

    // The original url for the image.
    optional string url = 3;
  }

  // The images referenced in the HTML.
  repeated Image image = 4;

  // Title for the current page.
  optional string title = 5;

  message DebugInfo {
    // Contains the log from the JS distiller.
    optional string log = 1;
  }

  // Debug information about this page.
  optional DebugInfo debug_info = 6;

  // text directionality
  optional string text_direction = 7;

  message PaginationInfo {
    optional string next_page = 1;
    optional string prev_page = 2;
    optional string canonical_page = 3;
    // #ifdef ARKWEB_READER_MODE
    optional string catalog_page = 4;
    // #endif ARKWEB_READER_MODE
  }

  // Pagination info for this page.
  optional PaginationInfo pagination_info = 8;

  // Removed obsolete field.
  reserved 9;

  // #ifdef ARKWEB_READER_MODE
  message HwReadExtendFields {
    optional string book_name = 1;
    optional string chapter_name = 2;
    optional string description = 3;
    optional string img_url = 4;
    optional string author = 5;
    optional string content = 6;
    optional string category = 7;
    optional string last_chapter_name = 8;
    optional string last_chapter_url = 9;
    optional PaginationInfo content_info = 10;

    message CatalogPageInfo {
      message ChapterInfo {
        optional string chapter_name = 1;
        optional string chapter_url = 2;
      }
      repeated ChapterInfo latest_chapters = 1;
      repeated ChapterInfo all_chapters = 2;

      message CatalogPaginationInfo {
        // 目录翻页
        // 下一个目录页链接
        optional string next_catalog_page = 1;
        // 上一个目录页链接
        optional string prev_catalog_page = 2;
        // 查看完整目录页链接
        optional string whole_catalog_page = 3;
        // 所有目录分页链接列表(支持目录页随机翻页)
        message CatalogPageContent {
          optional string page_name = 1;
          optional string page_url = 2;
          optional bool selected = 3;
        }
        repeated CatalogPageContent all_catalog_pages = 4;
      }
      optional CatalogPaginationInfo pagination_info = 3;
    }
    optional CatalogPageInfo catalog_info = 11;
    
    optional string start_read_link = 12;
    optional bool finished_status = 13;
    
    message TimingInfo {
      optional double distill_time = 1;
      optional double total_time = 2;
    }
    optional TimingInfo timing_info = 14;

    message HwDistilledResult {
      optional int32 code = 1;
      optional string message = 2;
    }
    optional HwDistilledResult distilled_result = 15;
  }
  optional HwReadExtendFields flat_fields = 12;
  // #endif ARKWEB_READER_MODE
}
