# Copyright 2022 The Huawei Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

if (is_ohos) {
  import("//build/config/ohos/config.gni")
  source_set("ohos") {
    visibility = [
      "//media",
      "//media/filters",
    ]

    sources = [
      "ohos_media_decoder_bridge_impl.cc",
      "ohos_media_decoder_bridge_impl.h",
      "ohos_media_player_bridge.cc",
      "ohos_media_player_bridge.h",
      "ohos_media_player_callback.cc",
      "ohos_media_player_callback.h",
      "ohos_media_player_listener.cc",
      "ohos_media_player_listener.h",
      "ohos_media_codec_bridge_impl.cc",
      "ohos_media_codec_bridge_impl.h",
      "ohos_media_codec_bridge.h",
      "ohos_media_resource_getter.cc",
      "ohos_media_resource_getter.h",
      "ohos_media_codec_util.cc",
      "ohos_media_codec_util.h",
      "buffer_flush_config_adapter_impl.cc",
      "buffer_flush_config_adapter_impl.h",
      "buffer_request_config_adapter_impl.cc",
      "buffer_request_config_adapter_impl.h",
      "codec_config_para_adapter_impl.cc",
      "codec_config_para_adapter_impl.h",
      "decoder_format_adapter_impl.cc",
      "decoder_format_adapter_impl.h",
      "ohos_media_player_recorder.cc",
      "ohos_media_player_recorder.h",
    ]

    if (defined(ohos_enable_cdm) && ohos_enable_cdm) {
      sources += [
        "ohos_cdm_factory.cc",
        "ohos_cdm_factory.h",
        "ohos_media_crypto_context_impl.cc",
        "ohos_media_crypto_context_impl.h",
        "ohos_media_crypto_context.h",
        "ohos_media_drm_bridge_client.cc",
        "ohos_media_drm_bridge_client.h",
        "ohos_media_drm_bridge_delegate.cc",
        "ohos_media_drm_bridge_delegate.h",
        "ohos_media_drm_bridge_factory.cc",
        "ohos_media_drm_bridge_factory.h",
        "ohos_media_drm_bridge.cc",
        "ohos_media_drm_bridge.h",
        "ohos_media_drm_storage_bridge.cc",
        "ohos_media_drm_storage_bridge.h",
      ]
    }

    configs += [ "//media:subcomponent_config" ]

    if (product_name == "rk3568") {
      defines = [ "RK3568" ]
    }

    deps = [
      "//media/base",
      "//url",
    ]

    include_dirs = ohos_src_includes
    deps += [
      "//ohos_glue:ohos_adapter_glue_source",
    ]
  }
}

source_set("unit_tests") {
  testonly = true
  sources = [ "buffer_flush_config_adapter_impl_unittest.cc" ]

  include_dirs = ohos_src_includes
  deps = [
    "//ohos_glue:ohos_adapter_glue_source",
    "//testing/gmock",
    "//testing/gtest",
  ]
}
