/* Generated by lastchange.py, do not edit.*/

#ifndef GPU_WEBGPU_DAWN_COMMIT_HASH_H_
#define GPU_WEBGPU_DAWN_COMMIT_HASH_H_

#define DAWN_COMMIT_HASH "0223916e3a572e7c264d0b8da5f077556e660871"

#endif  // GPU_WEBGPU_DAWN_COMMIT_HASH_H_
