/* Generated by lastchange.py, do not edit.*/

#ifndef GPU_WEBGPU_DAWN_COMMIT_HASH_H_
#define GPU_WEBGPU_DAWN_COMMIT_HASH_H_

#define DAWN_COMMIT_HASH "7df710dc8ae8618c317b52691fcd45b19037b2ba"

#endif  // GPU_WEBGPU_DAWN_COMMIT_HASH_H_
