# Copyright (c) 2025 Huawei Device Co., Ltd.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

config("arkweb_system_properties_config") {
  ldflags = [ "-Wl,--wrap=IsPcDevice" ]
}

config("blink_renderer_config") {
  ldflags = [ "-Wl,--wrap=IsTabletDevice" ]
}

config("arkweb_base_unittest_config") {
  ldflags = ["-Wl,--wrap=OH_FileUri_GetPathFromUri", 
  "-Wl,--wrap=OH_FileUri_GetFileName",
  "-Wl,--wrap=OH_CommonEvent_CreateSubscribeInfo",
  "-Wl,--wrap=OH_CommonEvent_CreateSubscriber",
  "-Wl,--wrap=OH_CommonEvent_Subscribe",
  "-Wl,--wrap=OH_CommonEvent_DestroySubscribeInfo",
  "-Wl,--wrap=OH_CommonEvent_DestroySubscriber",
  "-Wl,--wrap=OH_BatteryInfo_GetCapacity",
  "-Wl,--wrap=OH_BatteryInfo_GetPluggedType",
  "-Wl,--wrap=OH_AudioCapturer_Start",
  "-Wl,--wrap=OH_AudioCapturer_Stop",
  "-Wl,--wrap=OH_AudioCapturer_Release",
  "-Wl,--wrap=OH_AudioCapturer_GetFrameSizeInCallback",
  "-Wl,--wrap=OH_AudioCapturer_GetTimestamp",
  "-Wl,--wrap=OH_AudioStreamBuilder_Create",
  "-Wl,--wrap=OH_AudioStreamBuilder_SetSamplingRate",
  "-Wl,--wrap=OH_AudioStreamBuilder_Destroy",
  "-Wl,--wrap=OH_AudioStreamBuilder_SetSampleFormat",
  "-Wl,--wrap=OH_AudioStreamBuilder_SetEncodingType",
  "-Wl,--wrap=OH_AudioStreamBuilder_SetChannelCount",
  "-Wl,--wrap=OH_AudioStreamBuilder_SetCapturerInfo",
  "-Wl,--wrap=OH_AudioStreamBuilder_SetLatencyMode",
  "-Wl,--wrap=OH_AudioStreamBuilder_SetCapturerCallback",
  "-Wl,--wrap=OH_AudioStreamBuilder_GenerateCapturer",
  "-Wl,--wrap=OH_CommonEvent_UnSubscribe",
  ]

  ldflags += [ 
    "-Wl,--wrap=OsVersion",
    "-Wl,--wrap=CompatibleDeviceType",
    "-Wl,--wrap=IsMobileDevice",
    "-Wl,--wrap=IsTabletDevice",
    "-Wl,--wrap=IsPcDevice",
    "-Wl,--wrap=BaseOsName",
    "-Wl,--wrap=MajorVersion",
    "-Wl,--wrap=SeniorVersion",
  ]
}