# Copyright 2023 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

assert(is_ohos)

component("ohos") {
  output_name = "ui_base_ime_ohos"

  sources = [
    "input_method_ohos.cc",
    "input_method_ohos.h",
    "input_method_ohos_manager.cc",
    "input_method_ohos_manager.h"
  ]

  defines = [ "IS_UI_BASE_IME_OHOS_IMPL" ]

  public_deps = [
    "//base",
    "//ui/base/ime",
    "//ui/events",
    "//ohos/adapter:adapter"
  ]

  libs = [
    "ohinputmethod",
  ]
}