import("//gpu/vulkan/features.gni")
import("//build/config/features.gni")

assert(is_ohos)

visibility = [ "//ui/ozone/*" ]

source_set("ohos") {
  sources = [
    "client_native_pixmap_factory_ohos.cc",
    "client_native_pixmap_factory_ohos.h",
    "common/ohos_util.cc",
    "common/ohos_util.h",
    "drag/ohos_desktop_window_move_client.cc",
    "drag/ohos_desktop_window_move_client.h",
    "drag/ohos_drag_manager.cc",
    "drag/ohos_drag_manager.h",
    "drag/ohos_move_loop_delegate.h",
    "drag/ohos_whole_screen_move_loop.cc",
    "drag/ohos_whole_screen_move_loop.h",
    "drag/ohos_window_drag_manager.cc",
    "drag/ohos_window_drag_manager.h",
    "gpu/gl_surface_egl_ohos.cc",
    "gpu/gl_surface_egl_ohos.h",
    "gpu/gl_surface_egl_readback_ohos.cc",
    "gpu/gl_surface_egl_readback_ohos.h",
    "gpu/ohos_surface_factory.cc",
    "gpu/ohos_surface_factory.h",
    "host/ohos_canvas_surface.cc",
    "host/ohos_canvas_surface.h",
    "host/ohos_cursor_utils.cc",
    "host/ohos_cursor_utils.h",
    "host/ohos_event_filter.cc",
    "host/ohos_event_filter.h",
    "host/ohos_event_source.cc",
    "host/ohos_event_source.h",
    "host/ohos_event_source_base.cc",
    "host/ohos_event_source_base.h",
    "host/ohos_event_source_node_handle.cc",
    "host/ohos_event_source_node_handle.h",
    "host/ohos_fake_window.cc",
    "host/ohos_fake_window.h",
    "host/ohos_pip_window.cc",
    "host/ohos_pip_window.h",
    "host/ohos_pip_window_manager.cc",
    "host/ohos_pip_window_manager.h",
    "host/ohos_popup.cc",
    "host/ohos_popup.h",
    "host/ohos_screen.cc",
    "host/ohos_screen.h",
    "host/ohos_toplevel_pad_window.cc",
    "host/ohos_toplevel_pad_window.h",
    "host/ohos_toplevel_window.cc",
    "host/ohos_toplevel_window.h",
    "host/ohos_window.cc",
    "host/ohos_window.h",
    "host/ohos_window_factory.cc",
    "host/ohos_window_manager.cc",
    "host/ohos_window_manager.h",
    "host/ohos_window_observer.cc",
    "host/ohos_window_observer.h",
    "ozone_platform_ohos.cc",
    "ozone_platform_ohos.h",
  ]

  defines = [ "OZONE_IMPLEMENTATION" ]

  deps = [
    "//base",
    "//gpu/vulkan:buildflags",
    "//ohos/adapter:adapter",
    "//skia",
    "//ui/accessibility:ax_enums_mojo",
    "//ui/base",
    "//ui/base/clipboard:clipboard_types",
    "//ui/base/cursor",
    "//ui/base/dragdrop:types",
    "//ui/base/ime",
    "//ui/base/ime/ohos",
    "//ui/base/mojom:mojom",
    "//ui/base/mojom:ui_base_types",
    "//ui/events",
    "//ui/events/ozone/layout",
    "//ui/events/platform",
    "//ui/gfx/geometry",
    "//ui/ozone:ozone_base",
    "//ui/ozone/common",
    "//ui/platform_window",
    "//ui/platform_window/wm",
  ]

  libs = [
    "ace_napi.z",
    "ace_ndk.z",
    "native_display_manager",
    "native_window",
    "native_window_manager",
    "native_buffer",
    "ohinput",
  ]
}

source_set("test_support") {
  testonly = true

  sources = [
    "test/ohos_ozone_ui_controls_test_helper.cc",
    "test/ohos_ozone_ui_controls_test_helper.h",
  ]

  deps = [
    "//ui/aura:aura",
  ]
}

source_set("ohos_window_unittests") {
  testonly = true
  sources = [
    "host/ohos_window_unittests.cc"
  ]

  deps = [
    ":ohos",
    "//base",
    "//base/test:test_support",
    "//gpu/vulkan:buildflags",
    "//skia",
    "//ui/accessibility:ax_enums_mojo",
    "//ui/base",
    "//ui/base/clipboard:clipboard_types",
    "//ui/base/cursor",
    "//ui/base/dragdrop:types",
    "//ui/base/ime",
    "//ui/base/ime/ohos",
    "//ui/base/mojom:mojom",
    "//ui/base/mojom:ui_base_types",
    "//ui/events",
    "//ui/events/ozone/layout",
    "//ui/events/platform",
    "//ui/gfx/geometry",
    "//ui/ozone:ozone_base",
    "//ui/ozone/common",
    "//ui/platform_window",
    "//ui/platform_window/wm",
    "//ohos/adapter/test:adapter_mock",
  ]

  libs = [
    "ace_napi.z",
    "ace_ndk.z",
    "native_window",
    "native_buffer",
    "native_window_manager",
    "ohinput",
  ]
}
