# Copyright (c) 2025 Huawei Device Co., Ltd. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
 
import("//build/config/ohos/config.gni")
 
component("res_sched") {
  sources = [
    "manager/background_manager_api_wrapper.h",
    "manager/background_manager_api_wrapper.cc",
    "manager/throttle_manager.h",
    "manager/throttle_manager.cc",
    "manager/res_api_wrapper.h",
    "manager/res_api_wrapper.cc",
    "res_sched.h",
    "res_sched.cc"
  ]
}